spring:
  application:
    name: kafka-demo
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: consumer-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: 'ru.volkov'

server:
  port: 8000